var EVIDENCE_CODES_ = Object.freeze({RESTOCK_RECEIPT:'RST-RCPT',RESTOCK_INVOICE:'RST-INV',CANVASS_QUOTE:'CAN-QUOTE',CANVASS_PHOTO:'CAN-PHOTO',DELIVERABLE_RECEIPT:'DEL-RCPT',DELIVERABLE_DELIVERY_PROOF:'DEL-PROOF',RELEASE_CONFIRMATION_PHOTO:'REL-PHOTO',LENDING_HANDOFF_PHOTO:'LND-OUT',LENDING_RETURN_PHOTO:'LND-RETURN',OTHER_SUPPORTING_DOCUMENT:'OTHER'});
var EVIDENCE_LABELS_ = Object.freeze({RESTOCK_RECEIPT:'Restock Receipt',RESTOCK_INVOICE:'Restock Invoice',CANVASS_QUOTE:'Canvass Quote',CANVASS_PHOTO:'Canvass Photo',DELIVERABLE_RECEIPT:'Deliverable Receipt',DELIVERABLE_DELIVERY_PROOF:'Deliverable Delivery Proof',RELEASE_CONFIRMATION_PHOTO:'Release Confirmation',LENDING_HANDOFF_PHOTO:'Lending Handoff',LENDING_RETURN_PHOTO:'Lending Return',OTHER_SUPPORTING_DOCUMENT:'Supporting Document'});
function evidencePermissionForType_(type){if(['RESTOCK_RECEIPT','RESTOCK_INVOICE','CANVASS_QUOTE','CANVASS_PHOTO','DELIVERABLE_RECEIPT','DELIVERABLE_DELIVERY_PROOF'].indexOf(type)>=0)return'Can_Receive';if(['RELEASE_CONFIRMATION_PHOTO','LENDING_HANDOFF_PHOTO','LENDING_RETURN_PHOTO'].indexOf(type)>=0)return'Can_Release';return'Can_Admin';}
function authorizeEvidenceUpload_(type){return requirePermission_(evidencePermissionForType_(type));}
function normalizedEvidenceFilename_(payload,evidenceId,timestamp){var type=requireText_(payload.evidenceType,'evidenceType'),code=EVIDENCE_CODES_[type];if(!code)throw appError_('UNSUPPORTED_EVIDENCE_TYPE','Unsupported evidence type.',false);var ext=extensionForMime_(payload.mimeType),related=sanitizeSystemToken_(payload.relatedEntityId),secondary=sanitizeSystemToken_(payload.secondaryId||payload.itemId||payload.eventItemId||payload.requestLineId||'NA'),stamp=Utilities.formatDate(timestamp||new Date(),HAU_CONFIG.TIMEZONE,'yyyyMMdd-HHmmss');return[code,related,secondary,stamp,sanitizeSystemToken_(evidenceId)].join('_').slice(0,180)+'.'+ext;}
function evidenceLabel_(payload,timestamp){var label=EVIDENCE_LABELS_[payload.evidenceType]||'Evidence',date=Utilities.formatDate(timestamp||new Date(),HAU_CONFIG.TIMEZONE,'yyyy-MM-dd HH:mm')+' PHT',parts=[label,sanitizeSystemToken_(payload.relatedEntityId)];if(payload.secondaryId||payload.itemId||payload.eventItemId||payload.requestLineId)parts.push(sanitizeSystemToken_(payload.secondaryId||payload.itemId||payload.eventItemId||payload.requestLineId));if(payload.supplierName&&payload.evidenceType==='CANVASS_QUOTE')parts.push(String(payload.supplierName).replace(/[|\r\n]/g,' ').slice(0,60));parts.push(date);return parts.join(' | ');}
function validateEvidencePayload_(payload){requireObject_(payload,'Evidence');var type=requireText_(payload.evidenceType,'evidenceType'),mime=requireText_(payload.mimeType,'mimeType');if(!EVIDENCE_CODES_[type])throw appError_('UNSUPPORTED_EVIDENCE_TYPE','Unsupported evidence type.',false);if(HAU_CONFIG.ALLOWED_MIME_TYPES.indexOf(mime)<0)throw appError_('UNSUPPORTED_FILE_TYPE','Allowed files are JPG, PNG, WEBP, and PDF.',false);var ext=String(payload.originalFileName||'').split('.').pop().toLowerCase(),expected=extensionForMime_(mime);if(mime==='image/jpeg'&&ext==='jpeg')ext='jpg';if(ext!==expected)throw appError_('MIME_EXTENSION_MISMATCH','File extension does not match its MIME type.',false);requireText_(payload.relatedEntityId,'relatedEntityId');return true;}
function uploadEvidence_(command,correlationId){var user=authorizeEvidenceUpload_(command&&command.evidenceType),key=requireIdempotency_(command),replay=idempotencyReplay_(key);if(replay)return Object.assign({idempotentReplay:true},replay);validateEvidencePayload_(command);var bytes=decodeEvidenceBytes_(command),size=bytes.length;if(size===0)throw appError_('EMPTY_FILE','The uploaded file is empty.',false);if(size>HAU_CONFIG.MAX_UPLOAD_BYTES)throw appError_('FILE_TOO_LARGE','The maximum upload size is 10 MB.',false,{maxBytes:HAU_CONFIG.MAX_UPLOAD_BYTES});var digest=sha256Hex_(bytes),duplicate=readObjects_(HAU_SHEETS.EVIDENCE).find(function(r){return String(r.SHA256)===digest&&String(r.Related_Entity_Type)===String(command.relatedEntityType||'')&&String(r.Related_Entity_ID)===String(command.relatedEntityId)&&String(r.Upload_Status)==='UPLOADED';});if(duplicate){audit_('DUPLICATE_EVIDENCE_ATTEMPT','EVIDENCE',duplicate.Evidence_ID,user,correlationId,{notes:'Digest matched existing evidence.'});var duplicateResult={evidenceId:duplicate.Evidence_ID,driveUrl:duplicate.Drive_URL,duplicate:true};return recordIdempotency_(key,duplicateResult,user,correlationId);}
  var id=allocateId_('EVD'),timestamp=new Date(),filename=normalizedEvidenceFilename_(command,id,timestamp),label=evidenceLabel_(command,timestamp),folder=folderForEvidence_(command.evidenceType),blob=Utilities.newBlob(bytes,command.mimeType,filename),file;
  try{file=folder.createFile(blob);file.setName(filename);file.setDescription(label);}catch(error){throw appError_('DRIVE_UPLOAD_FAILED','Evidence could not be uploaded. You may retry safely.',true);}
  var row={Evidence_ID:id,Created_At:nowIso_(),Evidence_Type:command.evidenceType,Evidence_Label:label,Original_File_Name:String(command.originalFileName||'').slice(0,255),Normalized_File_Name:filename,Mime_Type:command.mimeType,Size_Bytes:size,SHA256:digest,Drive_File_ID:file.getId(),Drive_Folder_ID:folder.getId(),Drive_URL:file.getUrl(),Related_Entity_Type:command.relatedEntityType||'',Related_Entity_ID:command.relatedEntityId,Request_ID:command.requestId||'',Request_Line_ID:command.requestLineId||'',Event_ID:command.eventId||'',Item_ID:command.itemId||'',Event_Item_ID:command.eventItemId||'',Supplier_ID:command.supplierId||'',Uploaded_By:user.User_ID||'PUBLIC',Upload_Status:'UPLOADED',Duplicate_Of:'',Notes:command.notes||''};
  try{appendObject_(HAU_SHEETS.EVIDENCE,row);}catch(error){try{appendObject_(HAU_SHEETS.EVIDENCE,row);}catch(second){try{moveToRecovery_(file);}catch(recovery){}throw appError_('EVIDENCE_METADATA_FAILED','The file was quarantined because its metadata could not be recorded.',true,{evidenceId:id});}}
  audit_('UPLOAD_EVIDENCE','EVIDENCE',id,user,correlationId,{after:{evidenceType:row.Evidence_Type,normalizedFileName:filename,relatedEntityId:row.Related_Entity_ID}});return recordIdempotency_(key,{evidenceId:id,evidenceLabel:label,normalizedFileName:filename,driveUrl:file.getUrl(),duplicate:false},user,correlationId);}
