var HAU_PORTAL_MODES_ = Object.freeze(['internal','request','lending']);
function normalizePortalMode_(value,requestOnly){var mode=String(value||'').trim().toLowerCase();if(!mode)mode=requestOnly?'request':'internal';if(HAU_PORTAL_MODES_.indexOf(mode)<0)throw appError_('INVALID_PORTAL_MODE','Portal mode must be internal, request, or lending.',false);return mode;}

function itemById_(itemId) { var item = findOne_(HAU_SHEETS.ITEMS, 'Item_ID', itemId); if (!item) throw appError_('ITEM_NOT_FOUND', 'Inventory item was not found.', false, { itemId:itemId }); return item; }
function assertTransactableItem_(item) { if (String(item.Status).toUpperCase() === 'VERIFY') throw appError_('ITEM_REQUIRES_VERIFICATION', 'This legacy item must be reconciled before it can be transacted.', false, { itemId:item.Item_ID }); if (String(item.Status).toUpperCase() !== 'ACTIVE') throw appError_('ITEM_INACTIVE', 'This inventory item is not active.', false, { itemId:item.Item_ID }); }
function ledgerForItem_(itemId) { return findAll_(HAU_SHEETS.LEDGER, function(r) { return String(r.Item_ID) === String(itemId) && String(r.Status || 'POSTED') === 'POSTED'; }); }
function eventLedger_(eventItemId) { return findAll_(HAU_SHEETS.LEDGER, function(r) { return String(r.Event_Item_ID) === String(eventItemId) && String(r.Status || 'POSTED') === 'POSTED'; }); }
function signedQuantity_(row) { if (row.Signed_Qty !== '' && row.Signed_Qty != null) return Number(row.Signed_Qty); return (String(row.Direction) === 'IN' ? 1 : -1) * Number(row.Quantity || 0); }
function onHand_(itemId) { var item=itemById_(itemId); return Number(item.Opening_Qty || 0) + ledgerForItem_(itemId).reduce(function(sum,row){return sum+signedQuantity_(row);},0); }
function eventOnHand_(eventItemId) { return eventLedger_(eventItemId).reduce(function(sum,row){return sum+signedQuantity_(row);},0); }
function reservedQuantity_(itemId) { return findAll_(HAU_SHEETS.RESERVATIONS,function(r){return String(r.Item_ID)===String(itemId)&&String(r.Status)==='ACTIVE';}).reduce(function(sum,r){return sum+Number(r.Quantity||0);},0); }
function availableToPromise_(itemId) { return onHand_(itemId) - reservedQuantity_(itemId); }
function appendLedger_(entry, user) {
  var row=ledgerRow_(entry,user);appendObject_(HAU_SHEETS.LEDGER,row);return row;
}
function ledgerRow_(entry,user) {
  var quantity=positiveNumber_(entry.quantity,'quantity'), direction=requireText_(entry.direction,'direction').toUpperCase(); if(['IN','OUT'].indexOf(direction)<0) throw appError_('VALIDATION_ERROR','direction must be IN or OUT.',false);
  var row={ Transaction_ID:allocateId_('TXN'), Created_At:nowIso_(), Type:requireText_(entry.type,'type'), Direction:direction, Item_ID:entry.itemId||'', Event_Item_ID:entry.eventItemId||'', Quantity:quantity, Unit:entry.unit||'', Signed_Qty:(direction==='IN'?1:-1)*quantity, Related_Entity_Type:entry.relatedEntityType||'', Related_Entity_ID:entry.relatedEntityId||'', Request_ID:entry.requestId||'', Event_ID:entry.eventId||'', Actor_User_ID:user&&user.User_ID||'SYSTEM', Idempotency_Key:entry.idempotencyKey||'', Notes:entry.notes||'', Reversal_Of:entry.reversalOf||'', Status:'POSTED' };
  return row;
}
function inventoryIndexes_(items) { var onHand={},reserved={};(items||[]).forEach(function(item){onHand[item.Item_ID]=Number(item.Opening_Qty||0);reserved[item.Item_ID]=0;});readObjects_(HAU_SHEETS.LEDGER).forEach(function(row){if(row.Item_ID&&String(row.Status||'POSTED')==='POSTED')onHand[row.Item_ID]=Number(onHand[row.Item_ID]||0)+signedQuantity_(row);});readObjects_(HAU_SHEETS.RESERVATIONS).forEach(function(row){if(row.Item_ID&&String(row.Status)==='ACTIVE')reserved[row.Item_ID]=Number(reserved[row.Item_ID]||0)+Number(row.Quantity||0);});return{onHand:onHand,reserved:reserved};}
function searchCatalog_(command, includeSensitive) { var q=String(command.query||'').toLowerCase().trim(), limit=Math.min(Number(command.limit||25),100),items=readObjects_(HAU_SHEETS.ITEMS),indexes=includeSensitive?inventoryIndexes_(items):null; return items.filter(function(i){ if(!includeSensitive&&String(i.Status)==='ARCHIVED')return false; var hay=[i.Item_ID,i.Item_Name,i.Aliases,i.Category,i.Stock_Area,i.Catalog_Type,i.Handling,i.Unit].join(' ').toLowerCase(); return !q||hay.indexOf(q)>=0; }).slice(0,limit).map(function(item){return includeSensitive?itemDto_(item,indexes):requesterItemDto_(item);}); }
function itemDto_(i,indexes) { var on=indexes?Number(indexes.onHand[i.Item_ID]||0):onHand_(i.Item_ID), reserved=indexes?Number(indexes.reserved[i.Item_ID]||0):reservedQuantity_(i.Item_ID); return { id:i.Item_ID, name:i.Item_Name, aliases:String(i.Aliases||'').split('|').filter(Boolean), category:i.Category, stockArea:i.Stock_Area, catalogType:i.Catalog_Type||normalizeCatalogType_('',i.Stock_Area), storageLocation:i.Storage_Location||'', handling:i.Handling, handlingCode:normalizeHandling_(i.Handling), unit:i.Unit, openingOnHand:Number(i.Opening_Qty||0), status:i.Status, onHand:on, reserved:reserved, availableToPromise:on-reserved, reorderThreshold:Number(i.Reorder_Threshold||0), lendingAudience:effectiveLendingAudience_(i), defaultLoanDays:i.Default_Loan_Days===''?'':Number(i.Default_Loan_Days||0), maximumLoanQuantity:i.Maximum_Loan_Qty===''?'':Number(i.Maximum_Loan_Qty||0), approvalRequired:booleanValue_(i.Approval_Required,true), updatedAt:i.Updated_At||'', updatedBy:i.Updated_By||'', notes:i.Notes||'', verificationNote:i.Verification_Note||'', legacy:{sheet:i.Legacy_Source_Sheet,row:i.Legacy_Source_Row,block:i.Legacy_Source_Block} }; }
function requesterItemDto_(i) { var status=String(i.Status||'').toUpperCase(),catalogType=i.Catalog_Type||(typeof normalizeCatalogType_==='function'?normalizeCatalogType_('',i.Stock_Area):(String(i.Stock_Area||'').toUpperCase()==='PANTRY'?'PANTRY':'OFFICE_INVENTORY'));return { id:i.Item_ID, name:i.Item_Name, aliases:String(i.Aliases||'').split('|').filter(Boolean), category:i.Category, catalogType:catalogType, handling:i.Handling, unit:i.Unit, status:status==='ACTIVE'?'ACTIVE':status==='VERIFY'?'VERIFY':'INACTIVE', availabilityProtected:true }; }
function requesterEventDto_(r){return{id:r.Event_ID,seriesId:r.Event_Series_ID,code:r.Series_Code,name:r.Event_Name,startAt:r.Start_At,endAt:r.End_At,venue:r.Venue,status:r.Status};}
function getBootstrapData_(command) {
  var portalMode=normalizePortalMode_(command.portalMode,Boolean(command.requestOnly));
  if(portalMode==='lending')return getLendingBootstrap_();
  var requestedRequestOnly=portalMode!=='internal', resolvedUser=requestedRequestOnly?null:resolveCurrentUser_();
  var requestOnly=requestedRequestOnly||!isInternalBootstrapUser_(resolvedUser), user=requestOnly?{User_ID:'PUBLIC',Display_Name:'Requester',Role:'REQUESTER',Active:true}:resolvedUser;
  var eventRows=readObjects_(HAU_SHEETS.EVENTS), seriesById={},allItemRows=readObjects_(HAU_SHEETS.ITEMS),itemRows=requestOnly?allItemRows.filter(function(i){return String(i.Status)!=='ARCHIVED';}):allItemRows,itemIndexes=inventoryIndexes_(itemRows);
  eventRows.forEach(function(row){var id=String(row.Event_Series_ID||'').trim();if(id&&!seriesById[id])seriesById[id]={id:id,code:row.Series_Code||'',name:row.Event_Series_Name||row.Event_Name||id,status:row.Status||'ACTIVE'};});
  var revision=requestOnly?null:getDataRevision_();
  var base={ version:HAU_CONFIG.APP_VERSION, schemaVersion:HAU_CONFIG.SCHEMA_VERSION, backendMode:'apps-script', environment:getConfigValue_('APP_ENV',false)||'STAGING', portalMode:requestOnly?'request':'internal', currentUser:{id:user.User_ID||'PUBLIC',displayName:user.Display_Name||'Requester',role:user.Role||'REQUESTER',committee:user.Committee||'',permissions:userPermissionsDto_(user)}, eventSeries:Object.keys(seriesById).map(function(id){return seriesById[id];}), events:requestOnly?eventRows.map(requesterEventDto_):eventRows.map(eventDto_), inventoryItems:requestOnly?itemRows.map(requesterItemDto_):itemRows.map(function(item){return itemDto_(item,itemIndexes);}), catalogAvailabilityProtected:requestOnly };
  if(revision){base.dataRevision=revision.revision;base.dataRevisionUpdatedAt=revision.updatedAt;}
  if(requestOnly){ ['requests','requestLines','reservations','ledgerTransactions','lendingTickets','releaseConfirmations','restockRecords','restockRequests','deliverables','canvassReferences','evidenceFiles','auditLog','statusHistory','roadmapMilestones'].forEach(function(name){base[name]=[];});return base; }
  var canvassRows=readObjects_(HAU_SHEETS.CANVASS),canvassByLine={},canvassByDeliverable={};canvassRows.forEach(function(row){if(row.Linked_Request_Line_ID)(canvassByLine[row.Linked_Request_Line_ID]=canvassByLine[row.Linked_Request_Line_ID]||[]).push(row.Canvass_ID);if(row.Linked_Deliverable_ID)(canvassByDeliverable[row.Linked_Deliverable_ID]=canvassByDeliverable[row.Linked_Deliverable_ID]||[]).push(row.Canvass_ID);});
  var historyRows=readObjects_(HAU_SHEETS.HISTORY).map(historyDto_),historyByEntity={};historyRows.forEach(function(row){var key=row.entityType+'|'+row.entityId;(historyByEntity[key]=historyByEntity[key]||[]).push(row);});var attach=function(dto,type){dto.statusHistory=historyByEntity[type+'|'+dto.id]||[];return dto;};
  base.requests=readObjects_(HAU_SHEETS.REQUESTS).map(function(row){return attach(requestDto_(row),'REQUEST');});
  base.requestLines=readObjects_(HAU_SHEETS.REQUEST_LINES).map(function(row){return attach(lineDto_(row),'REQUEST_LINE');});
  base.requestReviewQueue=base.requests.filter(function(row){return String(row.status)==='FOR_REVIEW';});
  base.reservations=readObjects_(HAU_SHEETS.RESERVATIONS).map(reservationDto_);
  base.ledgerTransactions=readObjects_(HAU_SHEETS.LEDGER).map(ledgerDto_);
  base.lendingTickets=readObjects_(HAU_SHEETS.LENDING).map(function(row){return attach(lendingDto_(row),'LENDING');});
  base.releaseConfirmations=readObjects_(HAU_SHEETS.RELEASES).map(function(row){return attach(releaseDto_(row),'RELEASE');});
  base.restockRecords=readObjects_(HAU_SHEETS.RESTOCK).map(function(row){return attach(restockDto_(row),'RESTOCK');});
  base.restockRequests=restockRequestDtos_(base.requests,base.requestLines,historyByEntity);
  base.deliverables=readObjects_(HAU_SHEETS.DELIVERABLES).map(function(row){return attach(deliverableDto_(row,canvassByLine,canvassByDeliverable),'DELIVERABLE');});
  base.canvassReferences=canvassRows.map(canvassDto_); base.evidenceFiles=readObjects_(HAU_SHEETS.EVIDENCE).map(evidenceDto_); base.auditLog=canPermission_(user,'Can_Admin')?readObjects_(HAU_SHEETS.AUDIT).map(auditDto_):[]; base.statusHistory=historyRows; base.roadmapMilestones=[]; return base;
}

function restockRequestDtos_(requests,lines,historyByEntity){var requestById={};(requests||[]).forEach(function(request){requestById[request.id]=request;});return(lines||[]).filter(function(line){var request=requestById[line.requestId];return request&&String(request.type)==='CATALOG_RESTOCK';}).map(function(line){var request=requestById[line.requestId],id='RRQ-'+String(line.id||'').replace(/^RL-?/,'');return{id:id,requestId:line.requestId,requestLineId:line.id,itemId:line.itemId,catalogType:request.catalogType||'',quantity:Number(line.quantity||0),unit:line.unit,requester:request.requesterName,department:request.department,neededAt:line.neededAt,status:line.status,assignedTo:'',evidenceStatus:'Missing',createdAt:line.createdAt,updatedAt:line.updatedAt,createdBy:request.createdBy||'',statusHistory:historyByEntity['REQUEST_LINE|'+line.id]||[]};});}
function eventDto_(r){return{id:r.Event_ID,seriesId:r.Event_Series_ID,code:r.Series_Code,name:r.Event_Name,startAt:r.Start_At,endAt:r.End_At,venue:r.Venue,owner:r.Owner_Committee,department:r.Department,status:r.Status};}
function requestDto_(r){return{id:r.Request_ID,type:r.Request_Type,stage:r.Request_Stage,parentRequestId:r.Parent_Request_ID,eventSeriesId:r.Event_Series_ID,eventId:r.Event_ID,catalogType:r.Catalog_Type,requesterName:r.Requester_Name,requesterEmail:r.Requester_Email,department:r.Department,priority:r.Priority,purpose:r.Purpose,status:r.Status,createdAt:r.Created_At,updatedAt:r.Updated_At};}
function lineDto_(r){return{id:r.Request_Line_ID,requestId:r.Request_ID,eventId:r.Event_ID,itemId:r.Item_ID,eventItemId:r.Event_Item_ID,description:r.Description,specification:r.Specification,category:r.Category,quantity:Number(r.Requested_Qty||0),unit:r.Unit,fulfillmentSource:r.Fulfillment_Source,splitGroupId:r.Split_Group_ID,neededAt:r.Needed_At,returnDue:r.Return_Due,releasedQuantity:Number(r.Released_Qty||0),receivedQuantity:Number(r.Received_Qty||0),status:r.Status,createdAt:r.Created_At,updatedAt:r.Updated_At};}
function reservationDto_(r){return{id:r.Reservation_ID,itemId:r.Item_ID,quantity:Number(r.Quantity||0),unit:r.Unit,requestLineId:r.Request_Line_ID,lendingTicketId:r.Lending_Ticket_ID,status:r.Status,createdAt:r.Created_At,updatedAt:r.Updated_At};}
function ledgerDto_(r){return{id:r.Transaction_ID,type:r.Type,direction:r.Direction,itemId:r.Item_ID,eventItemId:r.Event_Item_ID,quantity:Number(r.Quantity||0),relatedId:r.Related_Entity_ID,createdAt:r.Created_At,createdBy:r.Actor_User_ID,notes:r.Notes};}
function lendingDto_(r){var summary=lendingReturnSummary_(r.Lending_Ticket_ID,Number(r.Quantity||0));return{id:r.Lending_Ticket_ID,studentIdNumber:r.Student_ID_Number,borrowerName:r.Borrower_Name,borrowerType:r.Borrower_Type,department:r.Department_Organization,contact:r.Contact,itemId:r.Item_ID,quantity:Number(r.Quantity||0),unit:r.Unit,purpose:r.Purpose,dueAt:r.Due_At,ticketType:r.Ticket_Type,status:r.Status,createdAt:r.Created_At,updatedAt:r.Updated_At,returnSummary:summary};}
function deliverableDto_(r,byLine,byDeliverable){var linked=[].concat(byLine&&byLine[r.Request_Line_ID]||[],byDeliverable&&byDeliverable[r.Deliverable_ID]||[]).filter(function(id,index,array){return array.indexOf(id)===index;});return{id:r.Deliverable_ID,requestId:r.Request_ID,requestLineId:r.Request_Line_ID,eventId:r.Event_ID,itemId:r.Inventory_Match_ID,inventoryMatchId:r.Inventory_Match_ID,eventItemId:r.Event_Item_ID,itemSpec:r.Item_Spec,quantity:Number(r.Quantity_Requested||0),quantityReceived:Number(r.Quantity_Received||0),quantityReleased:Number(r.Quantity_Released||0),unit:r.Unit,fulfillmentSource:r.Fulfillment_Source,assignedCommittee:r.Assigned_Committee,assignedStaff:r.Assigned_Staff,linkedCanvassIds:linked,preferredCanvassId:r.Preferred_Canvass_ID,budgetStatus:r.Budget_Status,procurementStatus:r.Procurement_Status,status:r.Status,neededAt:r.Needed_At,createdAt:r.Created_At,updatedAt:r.Updated_At};}
function canvassDto_(r){return{id:r.Canvass_ID,linkedLineIds:r.Linked_Request_Line_ID?[r.Linked_Request_Line_ID]:[],supplierId:r.Supplier_ID,supplierName:r.Supplier_Name,location:r.Location,itemSpec:r.Item_Spec,price:Number(r.Price||0),unit:r.Unit,receiptStatus:r.Receipt_Status,supplierTin:r.Supplier_TIN,reliability:r.Reliability,checkedAt:r.Checked_At,sourceUrl:r.Source_URL,evidenceId:r.Evidence_ID,status:r.Status,priceHistory:(function(){try{return JSON.parse(r.Price_History_JSON||'[]');}catch(e){return[];}})()};}
function releaseDto_(r){var ids=[],quantities=[],units=[];try{ids=JSON.parse(r.Request_Line_IDs_JSON||'[]');quantities=JSON.parse(r.Quantities_JSON||'[]');units=JSON.parse(r.Units_JSON||'[]');}catch(e){}return{id:r.Release_ID,requestId:r.Request_ID,eventId:r.Event_ID,lendingTicketId:r.Lending_Ticket_ID,recipientName:r.Recipient_Name,recipientRole:r.Recipient_Role,department:r.Department,releasedBy:r.Released_By,releasedAt:r.Released_At,status:r.Status,evidenceId:r.Evidence_ID,notes:r.Notes,lineReleases:ids.map(function(id,index){return{requestLineId:id,quantity:Number(quantities[index]||0),unit:units[index]||''};}),createdAt:r.Created_At,updatedAt:r.Created_At};}
function restockDto_(r){return{id:r.Restock_ID,sourceRequestId:r.Source_Request_ID,sourceRequestLineId:r.Source_Request_Line_ID,itemId:r.Item_ID,quantity:Number(r.Quantity||0),unit:r.Unit,supplierId:r.Supplier_ID,supplierName:r.Supplier_Name,unitPrice:Number(r.Unit_Price||0),invoiceStatus:r.Invoice_Status,invoiceNumber:r.Invoice_Number,storageArea:r.Storage_Area,storageLocation:r.Storage_Location,evidenceId:r.Evidence_ID,status:r.Status,requestedAt:r.Requested_At,receivedAt:r.Received_At,createdAt:r.Created_At,updatedAt:r.Updated_At,createdBy:r.Received_By,notes:r.Notes};}
function evidenceDto_(r){return{id:r.Evidence_ID,evidenceType:r.Evidence_Type,label:r.Evidence_Label,relatedId:r.Related_Entity_ID,itemId:r.Item_ID,eventItemId:r.Event_Item_ID,name:r.Normalized_File_Name,mimeType:r.Mime_Type,size:Number(r.Size_Bytes||0),driveFileId:r.Drive_File_ID,url:r.Drive_URL,status:r.Upload_Status,createdAt:r.Created_At,createdBy:r.Uploaded_By};}
function historyDto_(r){return{id:r.History_ID,entityType:r.Entity_Type,entityId:r.Entity_ID,status:r.New_Status,previousStatus:r.Previous_Status,at:r.Changed_At,actor:r.Changed_By,note:r.Reason};}
function auditDto_(r){return{id:r.Audit_ID,action:r.Action,entityType:r.Entity_Type,entityId:r.Entity_ID,actor:r.Actor_User_ID,at:r.Created_At,note:r.Notes,correlationId:r.Correlation_ID};}

function postEmergencyIssue_(command, correlationId) {
  return withScriptLock_(function() {
    var user=requirePermission_('Can_Release'),key=requireIdempotency_(command),replay=idempotencyReplay_(key);
    if(replay)return Object.assign({idempotentReplay:true},replay);
    var item=itemById_(requireText_(command.itemId,'itemId'));assertTransactableItem_(item);
    var quantity=positiveNumber_(command.quantity,'quantity');
    requireText_(command.reason,'reason');requireText_(command.approver,'approver');
    if(onHand_(item.Item_ID)<quantity)throw appError_('INSUFFICIENT_STOCK','Physical stock is insufficient for this emergency issue.',false,{onHand:onHand_(item.Item_ID)});
    var reference='EMERGENCY-'+Utilities.getUuid().slice(0,8).toUpperCase();
    var tx=appendLedger_({type:'ISSUE',direction:'OUT',itemId:item.Item_ID,quantity:quantity,unit:item.Unit,relatedEntityType:'EMERGENCY_ISSUE',relatedEntityId:reference,idempotencyKey:key,notes:command.reason+' | Approver: '+command.approver},user);
    audit_('EMERGENCY_ISSUE','ITEM',item.Item_ID,user,correlationId,{after:{reference:reference,transactionId:tx.Transaction_ID,quantity:quantity,reconciliationDeadline:command.reconciliationDeadline||''},notes:command.reason});
    return recordIdempotency_(key,{reference:reference,transactionId:tx.Transaction_ID},user,correlationId);
  });
}

function postCycleCountAdjustment_(command, correlationId) {
  return withScriptLock_(function() {
    var user=requirePermission_('Can_Admin'),key=requireIdempotency_(command),replay=idempotencyReplay_(key);
    if(replay)return Object.assign({idempotentReplay:true},replay);
    var item=itemById_(requireText_(command.itemId,'itemId'));assertTransactableItem_(item);
    var physical=nonNegativeNumber_(command.physicalCount,'physicalCount'),expected=onHand_(item.Item_ID),difference=physical-expected;
    requireText_(command.reason,'reason');
    if(difference===0)return recordIdempotency_(key,{itemId:item.Item_ID,expected:expected,physicalCount:physical,adjustment:0},user,correlationId);
    var tx=appendLedger_({type:'CYCLE_COUNT_ADJUSTMENT',direction:difference>0?'IN':'OUT',itemId:item.Item_ID,quantity:Math.abs(difference),unit:item.Unit,relatedEntityType:'CYCLE_COUNT',relatedEntityId:command.countSessionId||key,idempotencyKey:key,notes:command.reason},user);
    audit_('CYCLE_COUNT_ADJUSTMENT','ITEM',item.Item_ID,user,correlationId,{before:{expected:expected},after:{physicalCount:physical,adjustment:difference,transactionId:tx.Transaction_ID},notes:command.reason});
    return recordIdempotency_(key,{itemId:item.Item_ID,expected:expected,physicalCount:physical,adjustment:difference,transactionId:tx.Transaction_ID},user,correlationId);
  });
}
